SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT ORDER BY 2;
SELECT * FROM TAB;

--1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);
SELECT * FROM TB_CATEGORY;

--2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);
SELECT * FROM TB_CLASS_TYPE;

--3.
ALTER TABLE TB_CATEGORY ADD CONSTRAINT PK_NAME PRIMARY KEY(NAME);

--4.
ALTER TABLE TB_CLASS_TYPE MODIFY NAME CONSTRAINT NAME_NN NOT NULL;

--5.
ALTER TABLE TB_CATEGORY MODIFY NAME CHAR(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NAME CHAR(20);
ALTER TABLE TB_CLASS_TYPE MODIFY NO VARCHAR2(10);

--6.
ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NAME TO CLASS_TYPE_NAME;
ALTER TABLE TB_CLASS_TYPE RENAME COLUMN NO TO CLASS_TYPE_NO;
SELECT * FROM TB_CATEGORY;
SELECT * FROM TB_CLASS_TYPE;

--7.
ALTER TABLE TB_CLASS_TYPE RENAME CONSTRAINT SYS_C007198 TO PK_NO;
DESC TB_CLASS_TYPE ;

--8.
INSERT INTO TB_CATEGORY VALUES ('공학','Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES ('의학','Y');
INSERT INTO TB_CATEGORY VALUES ('예체능','Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회','Y');
COMMIT;

--9. --에러
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CATEGORY;
ALTER TABLE TB_CATEGORY MODIFY CATEGORY_NAME VARCHAR2(40);
ALTER TABLE TB_DEPARTMENT ADD CONSTRAINT FK_DEPARTMENT_CATEGORY FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

--10.
SELECT * FROM TB_STUDENT ORDER BY 2;
GRANT CREATE VIEW TO HOME;

CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 학생이름, STUDENT_ADDRESS AS 주소
   FROM TB_STUDENT;
SELECT * FROM VW_학생일반정보;

--11.
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_PROFESSOR;

CREATE VIEW VW_지도면담
AS SELECT STUDENT_NAME AS 학생이름, DEPARTMENT_NAME AS 학과이름, PROFESSOR_NAME AS 지도교수이름
    FROM TB_STUDENT
    LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
    LEFT JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
    ORDER BY 학과이름;
SELECT * FROM VW_지도면담;

--12.
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(*) AS STUDENT_COUNT
FROM TB_DEPARTMENT
JOIN TB_STUDENT USING(DEPARTMENT_NO)
GROUP BY DEPARTMENT_NAME;
SELECT * FROM VW_학과별학생수;

--13.
SELECT * FROM TB_STUDENT ORDER BY 2;
SELECT * FROM VW_학생일반정보;
UPDATE VW_학생일반정보 SET 학생이름='김경찬' WHERE 학번='A213046';

--14.
CREATE VIEW VW_학생일반정보
AS SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 학생이름, STUDENT_ADDRESS AS 주소
   FROM TB_STUDENT WITH READ ONLY;

--15.
SELECT * FROM TB_GRADE;
SELECT * FROM TB_CLASS;

SELECT *
FROM(
    SELECT CLASS_NO AS 과목번호, CALSS_NAME AS 과목이름, COUNT(*) AS 누적수강생수(명)
    FROM TB_CLASS
    JOIN TB_GRADE USING(CLASS_NO)
    GROUP BY (CLASS_NO,CALSS_NAME)
    );

