--1.
SELECT STUDENT_NAME AS 학생이름, STUDENT_ADDRESS AS 주소지 FROM TB_STUDENT;

--2. 
SELECT STUDENT_NAME,STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN='Y'
ORDER BY STUDENT_SSN DESC;

--3.
SELECT STUDENT_NAME AS 학생이름,STUDENT_NO AS 학번, STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1)='9' AND SUBSTR(STUDENT_ADDRESS,1,3)='경기도' OR SUBSTR(STUDENT_ADDRESS,1,3)='강원도';

--4.
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO=005
ORDER BY PROFESSOR_SSN;

--5.
SELECT STUDENT_NO,ROUND(POINT,2)
FROM TB_GRADE
WHERE TERM_NO = 200402 AND CLASS_NO='C3118100'
ORDER BY 2 DESC;

--6.
SELECT STUDENT_NO,STUDENT_NAME,DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
ORDER BY 2;

--7.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);


--8.
SELECT DISTINCT CLASS_NAME, PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
ORDER BY PROFESSOR_NAME;


--9.(SKIP)
SELECT CLASS_NAME,PROFESSOR_NAME
FROM TB_CLASS
JOIN TB_PROFESSOR USING(DEPARTMENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY='인문사회'
ORDER BY 2;


--10.
SELECT STUDENT_NO AS 학번,STUDENT_NAME AS "학생 이름", ROUND(AVG(POINT),1) AS "전체 평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME='음악학과'
GROUP BY STUDENT_NO,STUDENT_NAME
ORDER BY 1;

--11.
SELECT DEPARTMENT_NAME AS 학과이름,STUDENT_NAME AS "학생 이름", PROFESSOR_NAME AS 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
WHERE STUDENT_NO='A313047';


--12.
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
JOIN TB_CLASS USING (CLASS_NO)
WHERE CLASS_NAME='인간관계론' AND SUBSTR(TERM_NO,1,4)=2007
ORDER BY 1;


--13.
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
WHERE CATEGORY='예체능' AND PROFESSOR_NO IS NULL
ORDER BY 2;

--14.
SELECT STUDENT_NAME AS 학생이름, NVL(PROFESSOR_NAME,'지도교수 미지정') AS 지도교수
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
RIGHT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO=PROFESSOR_NO
WHERE DEPARTMENT_NAME='서반아어학과'
ORDER BY STUDENT_NO;

--15.
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, DEPARTMENT_NAME AS "학과 이름", AVG(POINT) AS 평점
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE ABSENCE_YN='N'
HAVING AVG(POINT) >= 4.0
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
ORDER BY 1;


--16.
SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT),8)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME='환경조경학과' AND SUBSTR(CLASS_TYPE,1,2)='전공'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;


--17.
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE DEPARTMENT_NO=(SELECT DEPARTMENT_NO FROM TB_STUDENT WHERE STUDENT_NAME='최경희');


--18.

SELECT MAX(AVG(POINT)) FROM TB_GRADE GROUP BY STUDENT_NO; -- 제일 높은 평점
SELECT DEPARTMENT_NAME FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME='국어국문학과'; --국어국문학과 

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE DEPARTMENT_NAME='국어국문학과'
GROUP BY STUDENT_NO, STUDENT_NAME
HAVING AVG(POINT)= (SELECT MAX(AVG(POINT)) FROM TB_GRADE 
                    JOIN TB_STUDENT USING(STUDENT_NO)
                    JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
                    WHERE DEPARTMENT_NAME='국어국문학과'
                    GROUP BY STUDENT_NO);

--19.
SELECT DEPARTMENT_NAME AS "계열 학과명",ROUND(AVG(POINT),1) AS 전공평점
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CATEGORY='자연과학'
GROUP BY DEPARTMENT_NAME
ORDER BY 1;







SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT ORDER BY 2;
SELECT * FROM TAB;









