CREATE USER HOME IDENTIFIED BY HOME;
GRANT CONNECT TO HOME;
GRANT RESOURCE TO HOME;
SELECT * FROM TAB;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT;

--1.
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열
FROM TB_DEPARTMENT;

--2.
SELECT DEPARTMENT_NAME || '의 정원은' || CAPACITY ||'명 입니다.' AS "학과별 정원" 
FROM TB_DEPARTMENT;

--3.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO='001' AND ABSENCE_YN='Y' AND SUBSTR(STUDENT_SSN,8,1)='2';

--4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO='A513079' OR STUDENT_NO='A513090' OR STUDENT_NO='A513091'
 OR STUDENT_NO='A513110' OR STUDENT_NO='A513119'
ORDER BY STUDENT_NAME DESC;

--5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

--6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7.
SELECT *
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

--8.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY CATEGORY;

--10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN IS NOT NULL AND SUBSTR(ENTRANCE_DATE,1,2)='02'
ORDER BY STUDENT_NAME;
