SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_GRADE;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_STUDENT ORDER BY 2;
SELECT * FROM TAB;

--1.
UPDATE TB_CLASS SET CLASS_TYPE='전공필수' WHERE DEPARTMENT_NO=001;
UPDATE TB_CLASS SET CLASS_TYPE='전공선택' WHERE DEPARTMENT_NO=002;
UPDATE TB_CLASS SET CLASS_TYPE='교양필수' WHERE DEPARTMENT_NO=003;
UPDATE TB_CLASS SET CLASS_TYPE='교양선택' WHERE DEPARTMENT_NO=004;
UPDATE TB_CLASS SET CLASS_TYPE='논문지도' WHERE DEPARTMENT_NO=005;
SELECT * FROM TB_CLASS;

--2.
CREATE TABLE TB_학생일반정보 
AS SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 학생이름, STUDENT_ADDRESS AS 주소
FROM TB_STUDENT;
SELECT * FROM TB_학생일반정보;

--3. 
SELECT * FROM TB_STUDENT ORDER BY 2;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_DEPARTMENT;

CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 학생이름, SUBSTR(STUDENT_SSN,1,2) AS 출생년도, PROFESSOR_NAME AS 교수이름
FROM TB_STUDENT
LEFT JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
LEFT JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과';

--4.


--5.
UPDATE TB_STUDENT SET STUDENT_ADDRESS='서울시 종로구 숭인동 181-21' WHERE STUDENT_NO='A413042';
SELECT * FROM TB_STUDENT WHERE STUDENT_NO='A413042';

--6. 
UPDATE TB_STUDENT SET STUDENT_SSN=SUBSTR(STUDENT_SSN,1,6);
SELECT * FROM TB_STUDENT;

--7. 
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;

UPDATE TB_GRADE SET POINT=3.5 
WHERE STUDENT_NO=
(SELECT STUDENT_NO 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE STUDENT_NAME='김명훈' AND DEPARTMENT_NAME='의학과')
        AND TERM_NO=200501;

SELECT * FROM TB_GRADE
WHERE STUDENT_NO=
(SELECT STUDENT_NO 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE STUDENT_NAME='김명훈' AND DEPARTMENT_NAME='의학과')
        AND TERM_NO=200501;

--8. 
SELECT * FROM TB_GRADE WHERE STUDENT_NO='A445008';
SELECT * FROM TB_STUDENT;

DELETE FROM TB_GRADE
WHERE STUDENT_NO IN 
        (SELECT STUDENT_NO 
        FROM TB_STUDENT
        WHERE ABSENCE_YN='Y')
